#!/bin/bash

REFDIR=$HOME/Bureau/bibliographie
KEYWORDS=$@

clean_word () {
    if [[ $# -ne 1 ]]; then
        printf "\n Error: $0 needs one argument.\n"
        exit -1
    fi
    echo "$1" | sed 's/{//g' | sed 's/}//g' | sed 's/(//g' | sed 's/)//g' | sed 's/\[//g' | sed 's/\]//g' \
        | sed "s/'//" | sed 's/"//g' | sed 's/`//g' | sed 's/^//g' | sed 's/~//g' \
        | sed 's/\\\\L/L/g' | sed 's/\\\\l/l/g' | sed 's/\\//g' | sed 's/^\s*//' | sed 's/\s*$//'
}



for WORD in $KEYWORDS; do
        
done
