#!/bin/bash

REFDIR=$HOME/Bureau/bibliographie
KEYWORDS="$@"

KEYWORDS="$(sed 's/{//g' "$KEYWORDS" | sed 's/}//g' | sed 's/(//g' | sed 's/)//g' | sed 's/\[//g' \
    | sed 's/\]//g' | sed "s/'//" | sed 's/"//g' | sed 's/`//g' | sed 's/^//g' | sed 's/~//g' \ 
    | sed 's/\\\\L/L/g' | sed 's/\\\\l/l/g' | sed 's/\\//g' | sed 's/^\s*//' | sed 's/\s*$//' \ 
    | sed 's/[^0-9a-zA-Z]/ /g'\
    | tr '[:upper:]' '[:lower:]'\
    )"

            
GOTREF=$(ls "$REFDIR") 
for WORD in $KEYWORDS; do
    
done
