#!/bin/bash
# This script copies some homemade scripts concerning Vim-LaTeX suite to $TEXTOOLS/vim/

LOCAL=$HOME/local/
LOGDIR=$LOCAL/log/
LOG=$LOGDIR/textools.log
VIM=$HOME/.vim/
TEXTOOLS=$LOCAL/textools/

mkdir -p $LOGDIR


{
DATE=`date +"%Y-%m-%d-%H:%M:%S-%Z"`
printf "\n----------------------------------- $DATE ------------------------------------\n"

set -o xtrace  # print the commands before executing them

cp -r $VIM/ftplugin/latex-suite/templates $TEXTOOLS/vim/
cp -r $VIM/zscripts/*LaTeX* $TEXTOOLS/vim/
} >> $LOG 2>&1  # Redirect all output to $LOG
